name: Documentation CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - 'templates/**'
      - '**.md'
      - '.github/workflows/docs-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'templates/**'
      - '**.md'
      - '.github/workflows/docs-ci.yml'

jobs:
  validate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install -g markdownlint-cli@0.39.0
        npm install -g @mermaid-js/mermaid-cli@10.8.0

    - name: Lint Markdown files
      run: |
        markdownlint 'docs/**/*.md' 'templates/**/*.md' --config .markdownlint.json || true

    - name: Validate Mermaid diagrams
      run: |
        find docs -name "*.md" -exec grep -l "```mermaid" {} \; | while read file; do
          echo "Validating Mermaid diagrams in $file"
          # Extract and validate each mermaid block
          awk '/```mermaid/,/```/' "$file" | grep -v '```' > temp_diagram.mmd
          if [ -s temp_diagram.mmd ]; then
            mmdc -i temp_diagram.mmd -o output.png -q || echo "Warning: Mermaid validation failed in $file"
          fi
        done
        rm -f temp_diagram.mmd output.png

    - name: Check internal links
      run: |
        # Check that all internal links resolve
        for file in $(find docs -name "*.md"); do
          echo "Checking links in $file"
          grep -Eo '\[([^]]+)\]\(([^)]+)\)' "$file" | grep -Eo '\(([^)]+)\)' | tr -d '()' | while read link; do
            if [[ $link == /* ]] || [[ $link == http* ]] || [[ $link == #* ]]; then
              continue
            fi
            # Resolve relative links
            dir=$(dirname "$file")
            target="$dir/$link"
            if [[ ! -f "$target" ]] && [[ ! -f "${target}.md" ]]; then
              echo "Error: Broken link in $file: $link"
              exit 1
            fi
          done
        done

    - name: Validate YAML files
      run: |
        python -m pip install pyyaml
        python -c "
        import yaml
        import sys
        import glob

        errors = []
        for file in glob.glob('templates/**/*.yaml', recursive=True):
            try:
                with open(file, 'r') as f:
                    yaml.safe_load(f)
                print(f'✓ {file}')
            except Exception as e:
                errors.append(f'✗ {file}: {e}')

        if errors:
            print('\nErrors found:')
            for error in errors:
                print(error)
            sys.exit(1)
        else:
            print('\nAll YAML files are valid!')
        "

    - name: Check documentation completeness
      run: |
        # Ensure all required documentation files exist
        required_files=(
          "docs/overview.md"
          "docs/setup.md"
          "docs/security.md"
          "docs/backlog.md"
          "templates/spec-v2.yaml"
          "docs/spec-v2.md"
        )

        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "Error: Required file missing: $file"
            exit 1
          fi
          echo "✓ Found: $file"
        done

        # Check that module docs exist for main components
        modules=(
          "api-server"
          "article-pipeline"
          "topic-collector"
          "ai-generator"
          "wordpress-publisher"
          "frontend-architecture"
        )

        for module in "${modules[@]}"; do
          if [ ! -f "docs/modules/${module}.md" ]; then
            echo "Error: Module documentation missing: docs/modules/${module}.md"
            exit 1
          fi
          echo "✓ Found module doc: ${module}.md"
        done

    - name: Generate documentation report
      if: always()
      run: |
        echo "# Documentation Status Report" > docs-report.md
        echo "" >> docs-report.md
        echo "## File Count" >> docs-report.md
        echo "- Total Markdown files: $(find docs -name "*.md" | wc -l)" >> docs-report.md
        echo "- Total YAML templates: $(find templates -name "*.yaml" | wc -l)" >> docs-report.md
        echo "" >> docs-report.md
        echo "## Word Count" >> docs-report.md
        find docs -name "*.md" -exec wc -w {} + | tail -1 >> docs-report.md
        echo "" >> docs-report.md
        echo "## Mermaid Diagrams" >> docs-report.md
        echo "- Total diagrams: $(grep -r "```mermaid" docs | wc -l)" >> docs-report.md

    - name: Upload documentation report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: documentation-report
        path: docs-report.md

  # Create .markdownlint.json if it doesn't exist
  create-markdownlint-config:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Create .markdownlint.json
      run: |
        if [ ! -f .markdownlint.json ]; then
          cat > .markdownlint.json << 'EOF'
        {
          "default": true,
          "MD013": {
            "line_length": 120,
            "tables": false,
            "code_blocks": false
          },
          "MD033": {
            "allowed_elements": ["mermaid", "br", "p", "details", "summary"]
          },
          "MD041": false,
          "no-hard-tabs": false
        }
        EOF

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .markdownlint.json
          git diff --staged --quiet || git commit -m "Add .markdownlint.json configuration"
          git push
        fi